name: "Test Github Attestation + Goreleaser"

on:
  push:
    tags:
      - "*"      
  workflow_dispatch: # allows manual triggering

defaults:
  run:
    shell: bash

# Limit permissions of GITHUB_TOKEN.
jobs:
  do-release:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      id-token: write
      attestations: write  

    steps:        
      - name: Debug OIDC Env
        run: env | grep ACTIONS_ID_TOKEN    
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0
      - name: Run GoReleaser Build
        uses: goreleaser/goreleaser-action@f82d6c1c344bcacabba2c841718984797f664a6b
        with:
          distribution: goreleaser
          version: "~> 2"
          args: build --clean -f .goreleaser.yaml
      - name: Attest artifacts
        uses: actions/attest-build-provenance@v2 # v2.0
        with:
          subject-path: "dist/**"      
      - name: Run GoReleaser Release
        uses: goreleaser/goreleaser-action@f82d6c1c344bcacabba2c841718984797f664a6b
        with:
          distribution: goreleaser
          version: "~> 2"
          args: release --skip-validate --skip-build -f .goreleaser.yaml
