name: "Test Github Attestation + Goreleaser"

on:
  push:
    tags:
      - "*"      
  workflow_dispatch: # allows manual triggering

defaults:
  run:
    shell: bash

# Limit permissions of GITHUB_TOKEN.
jobs:
  do-release:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      id-token: write
      attestations: write  
      packages: write

    steps:        
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}          
      - name: Run GoReleaser Build
        id: goreleaser
        uses: goreleaser/goreleaser-action@f82d6c1c344bcacabba2c841718984797f664a6b
        with:
          distribution: goreleaser-pro
          version: "~> 2"
          args: release --clean --snapshot -f .goreleaser.yaml
        env:
          GORELEASER_KEY: ${{ secrets.GO_RELEASER }}          
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # Get the commit hash so we can get image digests
      - name: Get the short commit hash
        id: commit
        run: echo "::set-output name=short_commit::$(git rev-parse --short HEAD)"
          
      - name: Publish docker images
        id: docker_publish
        run: docker push sgress454/test-slack-webhook-action --all-tags

     # Pull the images back down to ensure we have the digest locally
      - name: Pull Docker images to get the digest
        run: docker pull ghcr.io/sgress454/test-slack-webhook-action:${{ steps.commit.outputs.short_commit }}
        
      - name: Docker image metadata
        id: image_metadata
        run: |
          echo "::set-output name=digest_fleet::$(docker inspect --format='{{index .RepoDigests 0}}' sgress454/test-slack-webhook-action:${{ steps.commit.outputs.short_commit }})"
      - name: Attest docker
        uses: actions/attest-build-provenance@619dbb2e03e0189af0c55118e7d3c5e129e99726 # v2.0
        with:
          subject-digest: ${{steps.image_metadata.outputs.digest}}
          subject-name: ${{steps.image_metadata.outputs.name}}
          push-to-registry: true